# Exercise 6b: numpy (continued)

## Aim: Get an overview of NumPy and some useful functions.

You can find the teaching resources for this lesson here: https://numpy.org/doc/stable/user/quickstart.html

### Issues covered:
- Shape manipulation: changing shape, stacking, splitting
- Copies and views

## 2. Shape manipulation

### Changing the shape

Q1. Use the following to create a 3x4 array: 
```
rg = np.random.default_rng(1)
a = np.floor(10 * rg.random((3, 4)))
```
Then use the `ravel` method to flatten the array and print it.

In [23]:
import numpy as np
rg = np.random.default_rng(1)
a = np.floor(10 * rg.random((3, 4)))
print(a)
a.ravel()

[[5. 9. 1. 9.]
 [3. 4. 8. 4.]
 [5. 0. 7. 5.]]


array([5., 9., 1., 9., 3., 4., 8., 4., 5., 0., 7., 5.])

Q2. Reshape the array so it has the shape (2,6) and print it.

In [28]:
b = a.reshape(2, 6)
b

array([[5., 9., 1., 9., 3., 4.],
       [8., 4., 5., 0., 7., 5.]])

Q3. Transpose the array and print it.

In [29]:
c = a.T
c

array([[5., 3., 5.],
       [9., 4., 0.],
       [1., 8., 7.],
       [9., 4., 5.]])

Q4. Use the resize method to change the shape of the array to (6,2). Notice the difference between reshape and resize.

In [30]:
# reshape returns the argument with a modified shape but resize modifies the array itself
a.resize(6,2)
a

array([[5., 9.],
       [1., 9.],
       [3., 4.],
       [8., 4.],
       [5., 0.],
       [7., 5.]])

Q5. Reshape the array to a shape of (3, -1) and print the reshaped array. Note what `-1` does here.

In [31]:
d =a.reshape(3, -1)
d

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

### Stacking

Q6.
- Write a function `stack_arrays` that takes two 2D arrays `a` and `b`, an axis argument and returns the arrays stacked along the specified axis. The function should handle the following cases:
    - Vertical stacking (`axis=0`): Stack the arrays along rows
    - Horizontal stacking (`axis=1`): Stack the arrays along columns
    - Column stacking (`axis=column`): Stack 1D arrays as columns of a 2D array if both a and b are 1D, if they are 2D stack them horizontally
    - If `axis` is set to any other value raise a `ValueError`
- Once you're happy with your function, try the test cases in the solutions to check your working!

In [24]:
import numpy as np

def stack_arrays(a, b, axis):
    if axis == 0:
        return np.vstack((a, b))
    elif axis == 1:
        return np.hstack((a,b))
    elif axis == 'column':
        return np.column_stack((a,b))
    else:
        raise ValueError("Invalid axis specified. Use 0, 1 or 'column'.")

# Test cases
a = np.array([[9,7], [5,2]])
b = np.array([[1., 9.], [5., 1.]])
c = np.array([4., 2.])
d = np.array([3., 8.])

# Vertical stacking
print("Vertical stacking:\n", stack_arrays(a, b, axis=0))

# Horizontal stacking
print("\nHorizontal stacking:\n", stack_arrays(a, b, axis=1))

# Column stacking for 1D arrays
print("\nColumn stacking (1D arrays):\n", stack_arrays(c, d, axis='column'))

Vertical stacking:
 [[9. 7.]
 [5. 2.]
 [1. 9.]
 [5. 1.]]

Horizontal stacking:
 [[9. 7. 1. 9.]
 [5. 2. 5. 1.]]

Column stacking (1D arrays):
 [[4. 3.]
 [2. 8.]]


### Splitting

Q7.
Given the following 2D array `b`:
```
rg = np.random.default_rng(42)
b = np.floor(10 * rg.random((2, 10)))
```
- Split the array equally using `np.hsplit` into 5 parts along the horizontal axis. Assign the resulting sub-arrays to a variable named `equal_splits`
- Split the array after the second and fifth columns using `np.hsplit`. Assign the resulting sub-arrays to a variable called `column_splits`.

In [25]:
rg = np.random.default_rng(42)
b = np.floor(10 * rg.random((2, 10)))

# Step 1: Split array b into 5 equal parts
equal_splits = np.hsplit(b, 5)

# Step 2: Split array after second and fifth columns
column_splits = np.hsplit(b, (2, 5))

# Print results
print("Equal Splits:", equal_splits)
print("Column Splits:", column_splits)

Equal Splits: [array([[7., 4.],
       [3., 9.]]), array([[8., 6.],
       [6., 8.]]), array([[0., 9.],
       [4., 2.]]), array([[7., 7.],
       [5., 0.]]), array([[1., 4.],
       [8., 6.]])]
Column Splits: [array([[7., 4.],
       [3., 9.]]), array([[8., 6., 0.],
       [6., 8., 4.]]), array([[9., 7., 7., 1., 4.],
       [2., 5., 0., 8., 6.]])]


## 3. Copies and views

Q8. Let's demonstrate No Copy:
- Write a function `test_no_copy()` that:
    - Creates a `3x3` Numpy array `a`.
    - Assigns `b=a` and checks if modifying `b` affects `a`.
    - Returns `True` if `b` is a reference to `a` i.e. no copy is made, and `False` otherwise
    - Hint: use `is` to verify if `a` and `b` are the same object.

In [34]:
def test_no_copy():
    a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    b = a
    b[0, 0] = 999
    return b is a  # Check if 'b' is a reference to 'a'

print("Testing no copy behavior:", test_no_copy())               # Expected: True

Testing no copy behavior: True


Q9. Let's demonstrate Shallow Copy:
- Write a function `test_shallow_copy()` that:
    - Creates a `3x3` Numpy array `a`.
    - Creates a shallow copy of `a` using `a.view()` and assigns it to `c`.
    - Modifies an element in `c` and checks if the change is reflected in `a`
    - Verifies that `a` and `c` are not the same object but share data
    - Returns `True` if the modification in `c` also modifies `a` and `False` otherwise
    - Hint: Use `is` to confirm `a` and `c` are different objects, and `c.base is a` to confirm shared data. 

In [35]:
def test_shallow_copy():
    a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    c = a.view()
    c[0, 0] = 999
    return c is not a and c.base is a  # Verify 'c' is a view of 'a'

print("Testing shallow copy behavior:", test_shallow_copy())     # Expected: True

Testing shallow copy behavior: True


Q10. Let's demonstrate Deep Copy: 
- Write a function `test_deep_copy()`that:
    - Creates a `3x3` Numpy array `a`
    - Creates a deep copy of `a` using `a.copy()` and assigns it to `d`
    - Modifies an element in `d` and checks if the change is reflected in `a`
    - Verifies that `a` and `d` do not share data
    - Returns `True` if `a` and `d` do not share data and `False` if they do. 

In [36]:
def test_deep_copy():
    a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    d = a.copy()
    d[0, 0] = 999
    return d.base is None and np.any(a != d)  # Check if 'd' is a true deep copy

print("Testing deep copy behavior:", test_deep_copy())           # Expected: True

Testing deep copy behavior: True


Q11. Let's demonstrate Memory Management: 
- Write a function `memory_management_example()` that:
    - Creates a large array `a` of 10 million elements
    - Creates a slice of `a` containing the first 10 elements and assigns it to `b`
    - Deletes `a` and observes what happens to `b`
    - Creates another slice of `a` containing the first 1- elements but it copies it deeply this time assigning it to `c`
    - Deletes `a` and observes if `c` is still accessible
    - Returns `True` if `b` cannot be accessed after deleting `a`, but `c` can and `False` otherwise
    - Hint: use a try-except block to handle errors from accessing `b` after deleting `a`

In [37]:
def memory_management_example():
    a = np.arange(int(1e7))
    b = a[:10]
    del a
    try:
        b_sum = b.sum()  # Check if 'b' is accessible after deleting 'a'
    except NameError:
        b_accessible = False
    else:
        b_accessible = True

    a = np.arange(int(1e7))  # Re-create 'a' for the next test
    c = a[:10].copy()
    del a
    try:
        c_sum = c.sum()  # Check if 'c' is accessible after deleting 'a'
    except NameError:
        c_accessible = False
    else:
        c_accessible = True

    return not b_accessible and c_accessible

print("Testing memory management example:", memory_management_example())  # Expected: True

Testing memory management example: False
