This is the notebook that was used for the recap session for the numpy material

Note that when doing the recap, some commands were edited and re-evaluated a number of times to demonstrate different options, so this is just a snapshot of however it ended up. It doesn't show everything that was tried.

In [ ]:
import numpy as np

In [8]:
f = np.array([[0, 1, 2, 31], [12.4,467, 12,2]])
print(f, f.dtype)

[[  0.    1.    2.   31. ]
 [ 12.4 467.   12.    2. ]] float64


In [10]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.arange(40,dtype=float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39.])

In [14]:
g = np.array((23,673,12,12))

In [15]:
g

array([ 23, 673,  12,  12])

In [16]:
g[2]

12

In [17]:
g[2] = 4
print(g)

[ 23 673   4  12]


In [20]:
g[1:4] = 10

In [21]:
g

array([23, 10, 10, 10])

In [22]:
f

array([[  0. ,   1. ,   2. ,  31. ],
       [ 12.4, 467. ,  12. ,   2. ]])

In [24]:
f[0, 1]

1.0

In [26]:
f[1, 1:3] = [3,5]

In [27]:
f

array([[ 0. ,  1. ,  2. , 31. ],
       [12.4,  3. ,  5. ,  2. ]])

In [28]:
np.size(f)

8

In [29]:
len(f)

2

In [30]:
np.shape(f)

(2, 4)

In [31]:
f.shape

(2, 4)

In [32]:
f.max()

31.0

In [33]:
np.max(f)

31.0

In [34]:
np.average(f)

7.05

In [35]:
f.average()

AttributeError: 'numpy.ndarray' object has no attribute 'average'

In [36]:
f.ravel()

array([ 0. ,  1. ,  2. , 31. , 12.4,  3. ,  5. ,  2. ])

In [37]:
f.repeat(5)

array([ 0. ,  0. ,  0. ,  0. ,  0. ,  1. ,  1. ,  1. ,  1. ,  1. ,  2. ,
        2. ,  2. ,  2. ,  2. , 31. , 31. , 31. , 31. , 31. , 12.4, 12.4,
       12.4, 12.4, 12.4,  3. ,  3. ,  3. ,  3. ,  3. ,  5. ,  5. ,  5. ,
        5. ,  5. ,  2. ,  2. ,  2. ,  2. ,  2. ])

In [39]:
np.repeat(f, 3, axis=1)

array([[ 0. ,  0. ,  0. ,  1. ,  1. ,  1. ,  2. ,  2. ,  2. , 31. , 31. ,
        31. ],
       [12.4, 12.4, 12.4,  3. ,  3. ,  3. ,  5. ,  5. ,  5. ,  2. ,  2. ,
         2. ]])

In [40]:
x = np.arange(4) + 10

In [41]:
y = np.arange(3) + 20

In [42]:
x

array([10, 11, 12, 13])

In [43]:
y

array([20, 21, 22])

In [44]:
x2d, y2d = np.meshgrid(x, y)

In [45]:
x2d

array([[10, 11, 12, 13],
       [10, 11, 12, 13],
       [10, 11, 12, 13]])

In [46]:
y2d

array([[20, 20, 20, 20],
       [21, 21, 21, 21],
       [22, 22, 22, 22]])

In [48]:
x2d * y2d

array([[200, 220, 240, 260],
       [210, 231, 252, 273],
       [220, 242, 264, 286]])

In [52]:
cond = np.logical_and(y2d > 20, y2d < 22)

In [53]:
cond

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [False, False, False, False]])

In [54]:
np.where(cond, x2d, -1)

array([[-1, -1, -1, -1],
       [10, 11, 12, 13],
       [-1, -1, -1, -1]])

In [55]:
import math

In [56]:
f

array([[ 0. ,  1. ,  2. , 31. ],
       [12.4,  3. ,  5. ,  2. ]])

In [57]:
math.exp(12.4)

242801.61749832364

In [58]:
np.exp(f)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.90488497e+13],
       [2.42801617e+05, 2.00855369e+01, 1.48413159e+02, 7.38905610e+00]])

In [61]:
import numpy.ma as MA

In [66]:
a = MA.masked_array([2,3,4,5,6],mask=[True,True,False,False,False],dtype=float)

In [67]:
a

masked_array(data=[--, --, 4.0, 5.0, 6.0],
             mask=[ True,  True, False, False, False],
       fill_value=1e+20)

In [68]:
b = MA.masked_array([12,13,14,15,16],mask=[True,False,True,False,False],dtype=float)

In [69]:
b

masked_array(data=[--, 13.0, --, 15.0, 16.0],
             mask=[ True, False,  True, False, False],
       fill_value=1e+20)

In [70]:
a * 2

masked_array(data=[--, --, 8.0, 10.0, 12.0],
             mask=[ True,  True, False, False, False],
       fill_value=1e+20)

In [71]:
a + b

masked_array(data=[--, --, --, 20.0, 22.0],
             mask=[ True,  True,  True, False, False],
       fill_value=1e+20)

In [73]:
print(type(a))
print(type(a.filled()))

<class 'numpy.ma.core.MaskedArray'>
<class 'numpy.ndarray'>
